### ISSUE TITLE
Possible installation without .exe?

### ISSUE THREAD

**Issue by stlct** [dumbeau/AutoHotPie#10]
First really nice tool i have to say,
is it possible to install this .ahk script without any .exe, just the pure ahk script?
i want to use this script with my work computer and but administration doesn't allow to install any software. we just have AHK pre-installed.

**Comment by dumbeau** [comment]
Happy you find it useful!

This will take some small tweaks just to make a version of the AHK script that doesn't need the settings UI app to exist (that part is not AHK so you won't be able to have the settings UI on your work machine).  You could create the settings file on a non-work machine, export the settings file and place it next to the PieMenu.ahk script after I make this update.  Would this solution work for you?

**Comment by stlct** [comment]
Wow, thanks for the fast reply.
Yeah, i guess this would work. I already use the script on my other machine. So this shouldnt be a problem to generate the settings file.

**Comment by dumbeau** [comment]
I've added a menu bar to [v1.0.10](https://github.com/dumbeau/AutoHotPie/releases).  In it you'll find 'File > Create portable package'.  Choose a folder to create the package and an 'AutoHotPie-Standalone' directory will be made containing the AHK script and dependencies along with a current settings file, just transfer this folder to your work machine.  PieMenu.exe (or any executables) are not be included, so it shouldn't set off any security flags.  Whenever you want to update the settings file for this portable version, just create a new settings file on the non-work machine, export it and replace the settings file in the portable folder on the work machine.  PieMenu.ahk will use whatever json file is in its directory for settings.

**Comment by stlct** [comment]
hey dumbeau,

i had time to try the standalone. unfortunately i get an error.
![image001](https://user-images.githubusercontent.com/36421045/156455837-1e51404b-bd28-4f0f-807d-1d6d671764e7.png)

do you know what causes this?

**Comment by dumbeau** [comment]
The only reason I'd think this error would pop up is if the installed AHK version doesn't have the "Switch" command.  Switch has had a few updates in AHK.  Try updating AHK on this machine and lmk if that does anything.

**Comment by stlct** [comment]
Alright, good to know. I just checked the version and it's version 1.1.24.0 from May 2016.
Understandable, that it doesn't work. I wrote a ticket to our IT department. Maybe they are allowed to update the AHK version for me.

thanks for your effort. i will let you know, if it works, when they allow a new version of AHK on my work pc.

**Comment by stlct** [comment]
It works. I could upgrade to the newest AHK Build, thanks to my IT department.
It's a bit complicated because i can't just copy .ahk or .json files via USB stick, but i managed to send me a .7z(7zip) file with the required files as .txt inside.
After extracting and renaming the files, i now have a running PieMenu.
Thank you so much for your work.

Now i just have to set it up the way i like it.
By sending files over and over again via mail until every file path and every icon is working.

**Comment by dumbeau** [comment]
Heck yeah!  Happy to hear something is working, even if it's my band-aid solution to getting around code-signing for the time being.  Thanks for being willing to deal with this non-ideal workflow for now.
