### ISSUE TITLE
Function Slice Hotkeys not working and Color picker issues

### ISSUE THREAD

**Issue by rexelbartolome** [dumbeau/AutoHotPie#11]
I've now tried using this for Google Sheets but apparently the Hotkeys assigned to the individual slices doesn't get detected at all and just gets sent as an ordinary key press to the program/browser. Also doesn't work even if there's no text field

https://user-images.githubusercontent.com/88552647/143777132-ded534be-3e21-4688-9874-fa58624eb127.mp4

Also the eyedropper doesn't work outside of the AHP UI and just sends a normal mouse click instead without capturing the clicked color.

https://user-images.githubusercontent.com/88552647/143777403-43fccbdf-24d8-4d39-b68f-e97017ed1a58.mp4

I also can't paste hexcodes from the clipboard to the hex mode version of the color picker. Pasting just deletes the current text

https://user-images.githubusercontent.com/88552647/143777545-5893e0ae-49db-4c69-8df2-1a76f5f6977a.mp4

**Comment by dumbeau** [comment]
Thanks for including videos. I'll try and get the hotkey issue fixed quick today but the color picker issue is mostly a limitation of using the 'system color picker', so that one will take a while longer.

**Comment by dumbeau** [comment]
The slice hotkeys should be fixed now (v1.0.11 has been updated).  If it doesn't work, export your settings file and send it to beau@beaugilles.com.

Next the color picker will be revamped, for the time being you'll have to type your hexcodes in.

**Comment by rexelbartolome** [comment]
Thanks! The slice hotkeys do in fact work for me now :D and I'll looking forward to the color picker change :)

**Comment by dumbeau** [comment]
[v1.0.12](url) Now has a native color picker and you can paste in hexcodes.  Feel free to reopen this if you run into issues with it.

![image](https://user-images.githubusercontent.com/36665762/145548628-3ad1637b-af8a-41d5-b4e4-726768cf56fe.png)
