### ISSUE TITLE
[feature request] Cat pie

### ISSUE THREAD

**Issue by yesfullman** [dumbeau/AutoHotPie#112]
Jut a cat shaped pie menu. where the ears do functions within the pie like dropdown or switching pies and the whiskers are pie slices. done bust idea i know.

**Comment by hced** [comment]
Funny but unnecessary request that bogs down developer's available brain resources perfecting the app.

**Comment by dumbeau** [comment]
Too late I've already spent the past 5 months on the cat menu...

Hahaha jk I'll happily take comments like this over agressive feature requests anyday.  (not that any of the feature requests I've gotten yet have been aggressive, I've just only seen some on other pages.)
