### ISSUE TITLE
Icons picker causing hang

### ISSUE THREAD

**Issue by GeneralMidi** [dumbeau/AutoHotPie#12]
Hey, really love this. 

I'm getting a hang when choosing an icon. See pic. I'm unable to click on an icon, and then the program won't let me go back. Save and run from menu closes the app, which then needs to be restarted.

![image](https://user-images.githubusercontent.com/47597511/144415917-8db80aa3-30b2-4253-97a2-8f27f650905e.png)

**Comment by dumbeau** [comment]
Yikes... thanks for the post I'll get on that one today.  Happy you find this thing useful!

**Comment by dumbeau** [comment]
I believe this is fixed in the updated release [v1.0.11)](https://github.com/dumbeau/AutoHotPie/releases/tag/v1.0.11)

Let me know if this works on your end.

**Comment by GeneralMidi** [comment]
Fixed!
