### ISSUE TITLE
Is it possible to transfer a menu system from a desktop to a laptop?

### ISSUE THREAD

**Issue by JScuss** [dumbeau/AutoHotPie#123]
Don't want to recreate the menu system from scratch.

**Comment by ryjacky** [comment]
You could export the setting into a .json file and import it in your laptop, you could find the buttons at the top menu bar. This is currently the only way to do that I guess.

**Comment by JScuss** [comment]
I was unable to find the buttons you mentioned above. However, I was able to copy the Autohotpie folder under the Appdata and replace the same folder on my laptop and this worked. Thanks for the response.

**Comment by mmikeww** [comment]
export settings menu item is right here:

![image](https://github.com/dumbeau/AutoHotPie/assets/1900684/23bb39e7-8946-41f0-ac49-f467e7fe8455)

copying appdata\autohotpie should work too

issue can be closed
