### ISSUE TITLE
Unable to trigger Pie-menu via device buttons

### ISSUE THREAD

**Issue by hced** [dumbeau/AutoHotPie#131]
**ISSUE**
After assigning pie-menu hotkeys to be fired from hardware devices (such as the ones listed below) the pie-menu would only flash <5 ms or (more commonly) just do nothing at all. All this while the same hotkey pressed on my keyboard would open the pie-menu as normal.

This issue seems to be effective using both Logitech MX Master 3S using Logi Options+ as well as Wacom Tablet software.

Is there something obvious that I'm missing here?

---
I'm on Windows 11 Pro (v10.0.22621) and using latest AHP v1.0.27-alpha. (As well as latest Logi Options+ and Wacom Center/Wacom Tablet drivers,)

**Comment by dumbeau** [comment]
So the wacom devices and the MX Master send their key-down and key-up events immediately whereas your keyboard sends key-down when pressed, and key-up when released. 

Try the "Hover over all selections" launchmode for buttons that work that way
![image](https://github.com/dumbeau/AutoHotPie/assets/36665762/550a0f41-a394-4227-9fcf-d136a673d8bf)

I've found that for the wacom tablet you can use the 4th and 5th click buttons to get the pen to properly send key-down and key-up in relation to the key press.  You might like that solution better, I'm not a huge fan of the "hover select" modes.

This is a common problem that comes up, however I wouldn't call it obvious, I need to create some way of detecting that somebody is trying to assign a key coming from a button that works like the wacom tablet/pen or MX master.

Closing, but feel free to ask me questions here.
