### ISSUE TITLE
Function help

### ISSUE THREAD

**Issue by Vndless** [dumbeau/AutoHotPie#134]
Hi your project is very cool ！
 can you add a function ？
 If I run this, it will paste a predefined text or code

**Comment by dumbeau** [comment]
1. Create an AHK script that you can pass arguments into.
2. Use the **"Run File"** function and select the ahk script.
3. Edit the text field by adding your arguments after the file path.

Example:

test.ahk
```autohotkey
MsgBox, %1%, %2%
exitapp
```
![image](https://github.com/dumbeau/AutoHotPie/assets/36665762/dce0e861-739e-4756-a944-42e2a51e11b8)
As you can see in the image above, you can reuse the same AHK script on multiple slices, but set different arguments in the "Run File" text field, which is effectively creating your own functions.

I'm happy you find this useful!
