### ISSUE TITLE
possible bug with send key

### ISSUE THREAD

**Issue by GeneralMidi** [dumbeau/AutoHotPie#14]
Hey, 

I assign a send key function. Later I decide to change it. It seems the new key I can delete, but the original remains... 

cheers

![image](https://user-images.githubusercontent.com/47597511/145583225-ce4e96f2-a2a3-4761-8f40-31e0ec6278b9.png)

**Comment by dumbeau** [comment]
it would make sense that any of keys could be deleted if there is more than one key in a sequence.  Good find 👍

**Comment by dumbeau** [comment]
This is fixed in [v1.0.13](https://github.com/dumbeau/AutoHotPie/releases).

When two or more keys are present, all the keys in the sequence can be deleted.  When only one is present, the key can be clicked to replace it, or a key can be added.
