### ISSUE TITLE
[Feature request] Add localization support

### ISSUE THREAD

**Issue by AlexSciFier** [dumbeau/AutoHotPie#156]
Hello, do you consider to add localization support? Apparently Bootstrap studio [has support](https://bootstrapstudio.io/docs/localization-testing-reflow.html#localization) for it. I know it won’t be easy to transfer all the text to localization requirements, but I think it will be a very useful feature.

**Comment by dumbeau** [comment]
Language support is something we're handling better for V2, as we actually have a proper localization class.

**Comment by AlexSciFier** [comment]
Ok, thank you!
