### ISSUE TITLE
bug - sub menus only open after center ring focussed

### ISSUE THREAD

**Issue by GeneralMidi** [dumbeau/AutoHotPie#16]
Based on my previous FR, I'm not sure about this particular one, but in the name of consistency, I thought I'd raise it. I'm quite certain the title and licecap cover the main issue. 

Perhaps this behaviour is intended. Not sure. See what you think.

![subs](https://user-images.githubusercontent.com/47597511/145672391-16f2e4cc-932e-4ba1-a927-6b0cdc67bb20.gif)

**Comment by dumbeau** [comment]
This is intended, the reason for that is when the user is going from slice to slice, it's more of an exploration movement, so I didn't want to send user to a submenu in that case.  When a user goes from the center to a submenu, this is much more likely to be a deliberate means of selecting the submenu. 

I think this is the most intuitive way for it to work with first-time users, but if this feels like an issue to you I could pretty easily add an option to make the submenu activate whenever it is hovered for that activation mode.  Lmk.

**Comment by GeneralMidi** [comment]
No, after playing now a bit, I like it as it is.
