### ISSUE TITLE
CTRL + SHIFT + ALT keys no longer works

### ISSUE THREAD

**Issue by OlaHaldor** [dumbeau/AutoHotPie#18]
With the latest release, 1.0.12-alpha, I can no longer assign combinations with CTRL, SHIFT or ALT, in any combination. Either one of them alone or in combination of two or three + any letter, number or function key.

**Comment by OlaHaldor** [comment]
Noooo... My mistake. It's been a long time and I didn't read the UI correct. Sorry to startle you. :D 

What I did wrong was click "Assign Function Hotkey". 
What I should have clicked was just below, in the "Function" area.

Perhaps they should be reordered? Or perhaps the "Function: None" should have a different label or.. Something to make it stand out to shout and scream "this is where you want to click to assign a shortcut to the slice" ?

And I as an end user should learn to read of course.. :D

**Comment by dumbeau** [comment]
Haha no worries, I'll try to think of a way to reorganize this because this 'misread' has come up a few times.  This and the 'Pie Enable key' are the two most common UI organization issues.

**Comment by dumbeau** [comment]
Quick fix for the time being in [v1.0.13](https://github.com/dumbeau/AutoHotPie/releases) , the 'Slice Hotkey' option was moved below the function selection section, considering this option is a lower priority for most users.
