### ISSUE TITLE
Allow Windows key to be used as modifier

### ISSUE THREAD

**Issue by dumbeau** [dumbeau/AutoHotPie#19]
The windows key will be added as an optional modifier.
![image](https://user-images.githubusercontent.com/36665762/149642502-08c107bc-75a6-453f-8250-5815d606b1e4.png)

**Comment by sgrodnik** [comment]
Am I right that now is not possible do it even though export-import of the settings file with manual editing of the latter? I've tried it (for ex. 'keys: "#1"' ) and got some sick behavior in the settings interface and functionality same as without any modifier.

**Comment by dumbeau** [comment]
Yeah the settings interface will probably read it wrong, and I didnt really code any error checking there so you'll just get wonky behavior.  But I think running the pie menus will still work if you manually change the key in the settings file.

I'm hoping to get an updated version out tomorrow or the next day though, so it shouldn't be long on this.

**Comment by dumbeau** [comment]
This has been added in [v1.0.16](https://github.com/dumbeau/AutoHotPie/releases).
