### ISSUE TITLE
[Feature Request] Integrate Material Design Icons Library

### ISSUE THREAD

**Issue by trankillity** [dumbeau/AutoHotPie#24]
Literally hundreds of icons free to use. Would be fantastic to have them added in to this killer app!

[Material Design Icons](https://fonts.google.com/icons)

**Comment by dumbeau** [comment]
Ope, yeah I'll do that.  I'll probably have to add a search functionality to the icon selection page then too.

**Comment by dumbeau** [comment]
Search functionality has been added in [v1.0.17](https://github.com/dumbeau/AutoHotPie/releases).  Material icons will be added in the next version.

**Comment by dumbeau** [comment]
Material icons have been added in [v1.0.18](https://github.com/dumbeau/AutoHotPie/releases).
I sifted through them to remove a lot of the redundant ones and a few I was positive wouldn't be useful, just to keep the more useful icons near the top.
