### ISSUE TITLE
Open URL function not working

### ISSUE THREAD

**Issue by vfxturjo** [dumbeau/AutoHotPie#26]
Hi.
I hope u r doing well

for some reason, opening URL is not working. I tried assigning -> https://www.youtube.com/ 

please check it when u r free

**Comment by dumbeau** [comment]
Ope, yeah I sure goofed on that function.  Thanks for finding that, should be able to fix this today.

**Comment by dumbeau** [comment]
This is fixed now in [v1.0.16](https://github.com/dumbeau/AutoHotPie/releases).  A new exe was uploaded.
