### ISSUE TITLE
Print screen | Send Key

### ISSUE THREAD

**Issue by mlovizio** [dumbeau/AutoHotPie#30]
I'm currently struggling to map the ´print screen´ function to a *Send Key* action, when AHP is listening for my keystroke to be asigned and I push ´print screen´, the screen is captured instead of AHP detecting the keystroke. 

- ¿Can this function be added to the *Special keys* menu?

**Comment by dumbeau** [comment]
Apparently there was a bug with detecting PrintScreen, so now pressing that key should work now in [v1.0.17](https://github.com/dumbeau/AutoHotPie/releases).  I also added PrintScreen to the special keys list.

**Comment by mlovizio** [comment]
> Apparently there was a bug with detecting PrintScreen, so now pressing that key should work now in [v1.0.17](https://github.com/dumbeau/AutoHotPie/releases). I also added PrintScreen to the special keys list.

# That whas FAST! 
Nice!

Now it recognizes the PrintScreen key well, the only issue I see is when picking it from the Special key list.

- When I pick PrintScreen it select "Volume Down"


https://user-images.githubusercontent.com/74993598/157458055-bcc8981d-61cd-486a-ae12-68fbff08ac4e.mp4

**Comment by dumbeau** [comment]
Yeah... you caught me.  I didn't even test my own fix lol.

Thanks for catching that!  I updated v1.0.17 again.

**Comment by mlovizio** [comment]
# LOL

No problem, I test it! 

Is the least I can do, this beauty is a must in any productivity toolset.
