### ISSUE TITLE
One-handed functionality feature request

### ISSUE THREAD

**Issue by rexelbartolome** [dumbeau/AutoHotPie#4]
A feature much like in Blender's pie menus where they don't necessarily need a mouse to still work, it can still be accessed through another keyboard shortcut such as the number row.

![image](https://user-images.githubusercontent.com/88552647/132102739-b57bc4af-82c9-4de5-8500-4cd02e1a0a80.png)

Blender's is a bit unintuitive though, since the numbers are inconsistent with their placement on the pie. Maybe we can set it to a more consistent one and hopefully something that's still reachable by the left hand side of the keyboard like `1 , 2 , 3 , 4` can be the first four functions then the next four functions would be `Q, W, E, R`. Maybe that would be the default but it could still be customizable so it could also cater to left handed people.

While I draw with my right hand then use shortcuts on the keyboard with the left, my girlfriend is left-handed and  she uses her right hand for the keyboard (resting on the right-hand side as well), so naturally she's having trouble getting used to the right-handed-people bias of some of the default shortcut keys. So I customized an Autohotpie for her with some pretty basic functions to help with that and I hope if this feature gets added, I can also customize `1234 QWER` keys for her as well 😊

**Comment by dumbeau** [comment]
Ooo yup that has to be in here.  User-assignable slice shortcut keys will be added to the new version with the Settings UI as this requires a lot of re-writing.  I'll post back here when this is up.

**Comment by rexelbartolome** [comment]
Glad to hear! And looking forward to it 😊

**Comment by dumbeau** [comment]
User-assignable slice hotkeys have been added to the v1.0.3-alpha pre-release:
https://github.com/dumbeau/AutoHotPie/releases

Slice hotkeys also include a visual hint and slice hotkeys can be chained by using submenus.  Any feedback is welcome.
![image](https://user-images.githubusercontent.com/36665762/141065222-6c79cdc4-b09d-427d-abe2-ce7d0728f701.png)
