### ISSUE TITLE
Shortcut link to Programs and Features (Control Panel)

### ISSUE THREAD

**Issue by CoreyCorza** [dumbeau/AutoHotPie#41]
Catastrophic failure!

**Comment by CoreyCorza** [comment]
Btw - AutoHotPie is sooo gooood. THANK YOU!!!

**Comment by CoreyCorza** [comment]
Oh hang on. Just the shortcut fails. 
No issue when calling control.exe from system32.
My bad

**Comment by dumbeau** [comment]
Happy you like it!  I'm still working on it so I wouldn't be surprised if bugs like this come up.  I'll close this, but I have a plan to add a custom functions 'function' later on for finnicky things like this.
