### ISSUE TITLE
Idea to handle The no key_up problem.

### ISSUE THREAD

**Issue by yesfullman** [dumbeau/AutoHotPie#48]
Been recently using this app(literally every other year i go on a hunt for something like this and finally found your app! yus!) I think i have some idea for the no key_up problem. The "Hover over all selections" option works.. but it also becomes to touchy. I think an alternative option could basically just act like the "hover over sub-menus, release on function" but instead you could simply click the button once to open the menu then again to exit(or go full blender and use left click/escape). so the app only needs to see the key_down input not the key_up. then its users choice to either have it auto apply when hovering outside the center/ for a given amount of time or to click the same button or mouse button in order to activate the action. might not be as fast but i think it would be an overall smoother experience and be prone to less accidental selections.

**Comment by dumbeau** [comment]
For sure!  That's a good solution.  So maybe a 4th activation mode called "Click Selections"?  I'll add this.

**Comment by dumbeau** [comment]
> (literally every other year i go on a hunt for something like this and finally found your app! yus!)

You and me both... I just happened to have a lot of time to kill when I went down that rabbit hole.

**Comment by dumbeau** [comment]
The "Click selections" activation mode has been added in [v1.0.19](https://github.com/dumbeau/AutoHotPie/releases)

**Comment by yesfullman** [comment]
> For sure! That's a good solution. So maybe a 4th activation mode called "Click Selections"? I'll add this.

oh- I was not expecting that honestly! lol heck yeah I ill try this out cant wait!

**Comment by yesfullman** [comment]
Ok so idk if I should type this here or make a new one. Buutttt 2 things.

1) idk how hard it is to fix, but as it works now this does not work with windows ink. which means with a pen and tablet you can now bind whatever buttons you want and have the menu come up and stay, but you do need to make sure its not making clicks using windows ink. But I can now use my tablet with these menus after changing that option within wacoms software so still a win!

2) I do have one extension to clicking / exiting. (this is arguably targeting more of the pen tab crowd(which i am slowly joining) and might help deal with the problem noted above) what if you could toggle the activation button to do one of three things once the menu is up, along side the mouse click:
    1) exit the menu( which would probably be the best use case for most people outside of it doing nothing)
    2) alternative click function(same as mouse but would make pen life easier)
    3)default state of nothing.( how it works now unless I am missing something)
    
    on that note this seriously just helped a lot. Im also trying to make use of this macro pad I have(blender even with the ui updates still just needs all the hotkeys and there isnt enough!) but it apparently doesn't send key up options. Im also starting to get into using a pen tab and once I installed this that was my immediate wall.... which is now gone for the most part! Im honestly about to radial menu everything like ive been wanting to do! lol.

**Comment by dumbeau** [comment]
> as it works now this does not work with windows ink.

I've been trying to figure this one out for a while, windows ink hates me. I've just been turning off windows ink.  Or I need a way to bypass windows ink whenever the pie menu is open.

> exit the menu( which would probably be the best use case for most people outside of it doing nothing)
> alternative click function(same as mouse but would make pen life easier)
> default state of nothing.( how it works now unless I am missing something)

I like this, so for the "Hover over selections" and "Click selections" launchmodes a dropdown selection for these three modes would be added.  I'll try adding this.

**Comment by yesfullman** [comment]
Awesome!

**Comment by dumbeau** [comment]
This has been added in v1.0.20.
