### ISSUE TITLE
Modifier Keys not detected when asked for Keystroke

### ISSUE THREAD

**Issue by rexelbartolome** [dumbeau/AutoHotPie#5]
I'm not sure if modifier keys are now a separate thing that you're going to implement (like how you made the Mouse click have available modifier buttons to toggle). But the program doesn't seem to detect that I'm pressing Ctrl, Shift or Alt, but it detects Capslock and Backspace. I guess the only workaround for now would be to have a separate script for those kinds of Keystrokes.

Though I would prefer if I'm not limited to those three keys, I sometimes use Windows button and any of the buttons on the left-hand side like Capslock, Tab, and Tilde. But of course, those three keys are what I use 90% of the time.

Other than that, a nifty UI is a complete understatement... This looks fantastic! Along with the animations, responsiveness to hover, and window size change and everything. Very much looking forward to the updates! I think the modifier keys is the only thing stopping me from transferring all my functions to this new release :D

**Comment by dumbeau** [comment]
Whoops... it's been a long night.  I was missing a single character in one variable that removed all the modifier key detection visuals.  Thanks for the heads up and for the nice words :)

This is now fixed in v1.0.4:
https://github.com/dumbeau/AutoHotPie/releases

**Comment by rexelbartolome** [comment]
Everything's working out smoothly! I'll be transferring some of my hotkeys now and let you know if I encounter any issues 😊 
Thanks so much!

I guess the only thing I was wondering was which file or folder do I need to make a back up of so I can save my settings if I ever switch to another PC?

**Comment by dumbeau** [comment]
> I guess the only thing I was wondering was which file or folder do I need to make a back up of so I can save my settings if I ever switch to another PC?

"C:\Users\{user}\AppData\Roaming\AutoHotPie\AHPSettings.json"
Maybe it would be good to have a settings export/import function, I find myself asking this question in just about every application I use.

**Comment by dumbeau** [comment]
There is now an import/export settings button: #6
