### ISSUE TITLE
[Bug] Round slider is missing from sub-menus

### ISSUE THREAD

**Issue by Sineval** [dumbeau/AutoHotPie#55]
The round slider in v1.0.20-alpha is working only for the main pie menu, but is not visible/usable in sub-menus as seen on screenshots:

Main menu:
![main_menu](https://user-images.githubusercontent.com/38625241/176758351-eceeece1-9bf8-4432-9496-2b0d93b28e5a.png)

Sub-menu:
![sub_menu](https://user-images.githubusercontent.com/38625241/176758533-f1796b2c-4553-48c5-b8c4-62ed2c96524a.png)

**Comment by dumbeau** [comment]
Ope, thanks for finding this one!  This has been hotfixed in v1.0.20.

The label roundness just applies to all menus considering I can't imagine that anybody is going to want different a label roundness for different menus.
