### ISSUE TITLE
[Bug] Issues with Pie Menu activation method "Hover over all selections"

### ISSUE THREAD

**Issue by Sineval** [dumbeau/AutoHotPie#56]
In my continuing quest of using Pie Menu with otherwise useless buttons 4 and 5 on MX Ergo, I have encountered 2 issues with the activation method "Hover over all selections".

Test menu is configured, as the following screenshot shows:
![image](https://user-images.githubusercontent.com/38625241/176850957-3dc398bd-0ddd-4611-8547-583d22a6f6bb.png)

Issues found:
1. Visual bug that does not show highlighting of the slices when moving the mouse after pie menu activation, unless you either go to a sub-menu, or you click LMB. The slices are activated on hover, but this lack of visual feedback is confusing.
2. When using cursed "mouse-buttons-that-send-up-and-down-events-wrongly" as an activator, the newly added option "In-menu hotkey action" does not work. It does work when using keyboard, so this looks like another case of detections issues 

EDIT: 
Adding missed context:
OS: Windows 10 Version 10.0.19044 Build 19044
Auto Hot Pie version: 1.0.20-alpha

**Comment by dumbeau** [comment]
Thanks for finding these!  I'll try and fix these.

**Comment by dumbeau** [comment]
> 1. Visual bug that does not show highlighting of the slices when moving the mouse after pie menu activation, unless you either go to a sub-menu, or you click LMB. The slices are activated on hover, but this lack of visual feedback is confusing.

I'm having trouble recreating this.  Could you send your settings file to caspergilles@gmail.com?  You can create the file by going to File > Export Settings.

> 2. When using cursed "mouse-buttons-that-send-up-and-down-events-wrongly" as an activator, the newly added option "In-menu hotkey action" does not work. It does work when using keyboard, so this looks like another case of detections issues.

I can see why this wouldn't work, but it's fixable on my end.  This one may take a while, but I'll do it because you appreciate comic sans as a font.

**Comment by Sineval** [comment]
E-mail sent.

> you appreciate comic sans as a font.

How could I use anything else, when Comic Sans MS fits so perfectly with rounded labels? ;)

**Comment by dumbeau** [comment]
This uncovered quite a few other issues but I am actively working on this, if you want a temporary fix for now, set the Label Delay value to a very small number besides 0.

Thank you for finding this, I have no clue how I never noticed this.

**Comment by Sineval** [comment]
Can confirm, the Label Delay of 0.1 (the smallest it can go) fixes this issue, so we have a workaround working 👍

**Comment by dumbeau** [comment]
Whew, ended up not being too difficult.  This is fixed in v1.0.21.
