### ISSUE TITLE
Where are profiles stored?

### ISSUE THREAD

**Issue by OlaHaldor** [dumbeau/AutoHotPie#6]
Where are the profiles I create stored? Perhaps a "export" and "import" profiles button could be added to the GUI so it's easy to move between home and work/laptop etc. :)

**Comment by dumbeau** [comment]
I ask myself this question with every piece of software I use, good idea.  A settings import/export button will be added to the settings page.

**Comment by dumbeau** [comment]
At the moment, the settings file is stored in 
C:\Users\{username}\AppData\Roaming\AutoHotPie\AHPSettings.json

**Comment by dumbeau** [comment]
[v1.0.5-alpha](https://github.com/dumbeau/AutoHotPie/releases) has an "Import Settings" and "Export settings" button in the global settings page.
![image](https://user-images.githubusercontent.com/36665762/141423889-73097130-a10e-453e-9fa4-9b4aec3ddb84.png)
