### ISSUE TITLE
[Bug] Pie menu does not scale properly with max Menu Appearance sliders.

### ISSUE THREAD

**Issue by Sineval** [dumbeau/AutoHotPie#62]
Another one from me ;)

When setting appearance bars like so:
![image](https://user-images.githubusercontent.com/38625241/179402757-d328fff2-4e44-4a0d-ad3a-3e881d68b5ec.png)

The lowest slice label is actually cropped:
![image](https://user-images.githubusercontent.com/38625241/179402778-c17d4307-6e99-4b3d-9241-70c57dcd4498.png)

In fact, setting all the values to max causes the menu to look like this:
![image](https://user-images.githubusercontent.com/38625241/179402840-c3d97769-df23-42e9-b100-d7c8c5a816dd.png)

EDIT:
Forgot to mention:
Auto Hot Pie version: 1.0.21-alpha and 1.0.22-alpha
Desktop Resolution: 3840x2160

**Comment by dumbeau** [comment]
This is fixed in [v1.0.23](https://github.com/dumbeau/AutoHotPie/releases)
