### ISSUE TITLE
[Bug] Label Delay does not work in sub-menus

### ISSUE THREAD

**Issue by Sineval** [dumbeau/AutoHotPie#63]
When looking into ways of making the transfer between sub-menus less jarring and prone to accidental slice activation when using "Hover over all selections" Activation Type, I noticed that "Label Delay" only works for main-menu. Sub-menus slice labels are shown instantly regardless of the delay set.

Context:
Auto Hot Pie version: 1.0.22-alpha

**Comment by dumbeau** [comment]
This is fixed in [v1.0.23](https://github.com/dumbeau/AutoHotPie/releases)
