### ISSUE TITLE
Add profiles by grabbing the executable of a focused window.

### ISSUE THREAD

**Issue by dumbeau** [dumbeau/AutoHotPie#68]
In Pie-Menus V1, I used to have a method of adding profiles:
1. Click a button to start a 5 second countdown.
2. User focuses the desired window to add a profile for.
3. When the countdown ends, grab the executable of the focused window.
4. Prompt the user to add this profile.
![image](https://user-images.githubusercontent.com/36665762/188496565-7d3611d6-1384-4f9c-8ea8-14597d107518.png)

This is more convenient than searching for an executable, and it will ensure that the correct executable is acquired.

Adding UWP applications or other windows native programs results in grabbing an incorrect executable.  If you add a profile for notepad.exe in Win11, a profile will be created for that.  But when notepad.exe runs, the application that is running is actually "Notepad.exe".  Calculator has calc.exe but runs in "ApplicationFrameHost.exe".
![image](https://user-images.githubusercontent.com/36665762/188496184-82e07431-65a7-4b24-8f52-eb8479774958.png)

**Comment by xan2622** [comment]
It reminds me of [AltSnap](https://github.com/RamonUnch/AltSnap), which features a way to capture an application thanks to a "target icon"(that the user has to drag over the focussed application): 

![5948](https://user-images.githubusercontent.com/1732773/188498378-030493a6-2738-4e3d-b6f3-bae559bcb43c.jpg)

**Comment by dumbeau** [comment]
Dang, wish I saw that before I added this.

This has been added in [v1.0.24](https://github.com/dumbeau/AutoHotPie/releases/)
