### ISSUE TITLE
Will the number of buttons increase?

### ISSUE THREAD

**Issue by chenpaner** [dumbeau/AutoHotPie#75]
I am using this software in Rhino and it has improved my efficiency, but now there are only 6 buttons per ring, do you have any plans to allow users to customize the number of buttons? Or  can increase the number of rings, such as a 2-layer ring menu.

**Comment by dumbeau** [comment]
You can change the number of slices here:
<img width="220" alt="image" src="https://user-images.githubusercontent.com/36665762/202208003-894b5e17-0d9c-4ce5-ab71-76627ddfcf56.png">

Honestly the button isn't very obvious in the UI.
