### ISSUE TITLE
App-specific profiles?

### ISSUE THREAD

**Issue by shonilchi** [dumbeau/AutoHotPie#79]
I wanted to check if app-specific profiles can be configured in this application?  For example, when I have notepad activated, I press the Autohotpie hotkey and it gives me a set of options.  When I have Word open, I press the same hotkey and it gives me a different set of options.  Is this possible?

**Comment by Forikundo** [comment]
As far as I understood it does already do that

**Comment by dumbeau** [comment]
This has been answered, but just for future reference:
<img width="391" alt="image" src="https://user-images.githubusercontent.com/36665762/212764854-c7b6cbe2-4c6f-488a-917c-71ffd3fd5f30.png">
