### ISSUE TITLE
Add "Application Switch" function

### ISSUE THREAD

**Issue by dumbeau** [dumbeau/AutoHotPie#87]
There needs to be a function that runs an application if not running and focuses the window if currently running.  If the window is focused and this function is ran, it should tab between windows of the same application.

**Comment by zoltan-erdokovy** [comment]
Maybe window title/process name string matching could be used as an option? It would handle cases where I manually start certain versions of certain applications (Unreal Engine 4.27 or 5.0) but after that I'd want to focus the current instance.

**Comment by dumbeau** [comment]
> Maybe window title/process name string matching could be used as an option?
@zoltan-erdokovy Yes this is doable, having this written in AHKshould make this fairly simple.

Here are the options I see being available for the function:
- Exe destination
- Single instance or multiple instance program?
- If multiple instance program, open application in new window if a specified modifier key (ctrl, shift or alt) is held down.
- Additional scopes such as window title, process names or class names.

Feel free to add to it, I'm a fan of any effort to make the window taskbar redundant.

**Comment by dumbeau** [comment]
The "Switch Application" function has been added in v1.0.26.

There may be issues with it, please open these in a new issue.
