### ISSUE TITLE
REQ: add about section to show current version number

### ISSUE THREAD

**Issue by GeneralMidi** [dumbeau/AutoHotPie#90]
was looking to see if I had the latest version, and couldn't quickly identify what version I had installed.

![image](https://user-images.githubusercontent.com/47597511/223710851-66ad1af3-fee6-4150-98cd-ee16995c1d23.png)

**Comment by dumbeau** [comment]
I think it makes sense to have it in the help section and I'll move it there, but at the moment the version number can be found on the global settings page:
<img width="454" alt="image" src="https://user-images.githubusercontent.com/36665762/223714029-f2c3cb54-aa50-426a-8369-1907513c8aa7.png">

**Comment by dumbeau** [comment]
Added in v1.0.27
